name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Need to clone everything for the git tag tests.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        run: pip install pytest pytest-flake8 pytest-xdist pytest-openfiles pytest-cov

      - name: Install prereqs for setuptools
        run: pip install wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List installed packages
        shell: bash -l {0}
        run: |
          pip list -v

      - name: Build and install
        run: |
          python -m pip install -v -e .

      - name: Run tests
        run: |
          pytest -r a -v -n 3 --open-files --cov=tests --cov=lsst_versions --cov-report=xml --cov-report=term
