name: check Python formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Install isort and black
        run: pip install isort black

      - name: Run isort
        run: isort --check-only --diff python/ tests/

      - name: Run black
        run: black --check --verbose --diff python/ tests/
