name: Run mypy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the package to build.
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Install mypy
        run: pip install mypy types-setuptools

      - name: Build the package so that all dependencies are installed.
        run: pip install -v -e .

      - name: Run mypy
        run: mypy python
